### ISSUE TITLE
1.8.1 Fails unless configured with java and javascript formatter files

### ISSUE THREAD

**Issue by paulbandler** [velo/maven-formatter-plugin#23]
It doesn't appear that the java.xml and javascript.xml files are packaged with this plugin.  I have only been able to get it to work by searching out the source code and externally configuring the locations of these files, otherwise it fails with errors such as the one below.

[ERROR] Failed to execute goal com.marvinformatics.formatter:formatter-maven-plugin:1.8.1:format (default) on project trademodel: Unknown resource file:src/config/eclipse/formatter/java.xml -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.marvinformatics.formatter:formatter-maven-plugin:1.8.1:format (default) on project trademodel: Unknown resource file:src/config/eclipse/formatter/java.xml
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unknown resource file:src/config/eclipse/formatter/java.xml
	at com.marvinformatics.formatter.FormatterMojo.getOptionsFromConfigFile(FormatterMojo.java:586)
	at com.marvinformatics.formatter.FormatterMojo.getFormattingOptions(FormatterMojo.java:553)
	at com.marvinformatics.formatter.FormatterMojo.createCodeFormatter(FormatterMojo.java:540)
	at com.marvinformatics.formatter.FormatterMojo.execute(FormatterMojo.java:261)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.marvinformatics.formatter.support.io.Resource$UnknownResourceException: Unknown resource file:src/config/eclipse/formatter/java.xml
	at com.marvinformatics.formatter.support.io.Resource$FileResource.toInputStream(Resource.java:168)
	at com.marvinformatics.formatter.support.io.Resource.asInputStream(Resource.java:51)
	at com.marvinformatics.formatter.FormatterMojo.getOptionsFromConfigFile(FormatterMojo.java:575)
	... 25 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by velo** [comment]
Can you try `1.9.1.RC1` and see how it goes?!

**Comment by velo** [comment]
Please try it on 1.9.1.RC2
